# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /tp/xpiese5/xpiese5002/projet_fpga/pgcd_vivado/prj/pgcd.cache/wt [current_project]
set_property parent.project_path /tp/xpiese5/xpiese5002/projet_fpga/pgcd_vivado/prj/pgcd.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /tp/xpiese5/xpiese5002/projet_fpga/pgcd_vivado/prj/pgcd.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /tp/xpiese5/xpiese5002/projet_fpga/compn.vhd
  /tp/xpiese5/xpiese5002/projet_fpga/genres.vhd
  /tp/xpiese5/xpiese5002/projet_fpga/genxy.vhd
  /tp/xpiese5/xpiese5002/projet_fpga/muxn.vhd
  /tp/xpiese5/xpiese5002/projet_fpga/pgcd_fsm.vhd
  /tp/xpiese5/xpiese5002/projet_fpga/regn.vhd
  /tp/xpiese5/xpiese5002/projet_fpga/sub.vhd
  /tp/xpiese5/xpiese5002/projet_fpga/subn.vhd
  /tp/xpiese5/xpiese5002/projet_fpga/pgcd_dp.vhd
  /tp/xpiese5/xpiese5002/projet_fpga/pgcd.vhd
  /tp/xpiese5/xpiese5002/projet_fpga/signal_synchronizer.vhd
  /tp/xpiese5/xpiese5002/projet_fpga/pgcd_simple_top.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /tp/xpiese5/xpiese5002/projet_fpga/pgcd_vivado/xdc/physical.xdc
set_property used_in_implementation false [get_files /tp/xpiese5/xpiese5002/projet_fpga/pgcd_vivado/xdc/physical.xdc]

read_xdc /tp/xpiese5/xpiese5002/projet_fpga/pgcd_vivado/xdc/timing.xdc
set_property used_in_implementation false [get_files /tp/xpiese5/xpiese5002/projet_fpga/pgcd_vivado/xdc/timing.xdc]


synth_design -top pgcd_simple_top -part xc7z020clg400-1


write_checkpoint -force -noxdef pgcd_simple_top.dcp

catch { report_utilization -file pgcd_simple_top_utilization_synth.rpt -pb pgcd_simple_top_utilization_synth.pb }
